
trigger:
- master

jobs:
  - job: 'iOSbuild'
    pool: 
      vmImage: 'macOS-10.13'
    displayName: 'Build IPA file'
    variables:
      scheme: 'rakBibi'
      sdk: 'iphoneos'
      configuration: 'Release'
      teamId: M5H46J4YP8
    steps:

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: 'evgeny.karasik@gmail.com_cert.p12'
          #certPwd: $(P12Password)

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provProfileSecureFile: 'evgeny.karasik.mobileprovision'

      - task: Xcode@5
        inputs:
          sdk: '$(sdk)'
          scheme: '$(scheme)'
          configuration: '$(configuration)'
          xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
          exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
          archivePath: '$(Build.ArtifactStagingDirectory)/deploy'
          packageApp: true
          exportTeamId: $(teamId)
          exportOptions: 'auto'
          #exportMethod: 'development'
          signingOption: 'auto'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)/rakBibi.ipa'
          artifactName: 'rakBibi'
          
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script:
                python -m pip install --upgrade pip requests
                #pip install requests    

      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath'
          scriptPath: 'mc-uploadApp.py'
          arguments: 'demo.mobilecenter.io karasik@microfocus.com Welc0me11 $(agent.buildDirectory)/output/$(sdk)/$(configuration)/rakBibi.ipa'
