trigger:
- master

pool:
  vmImage: 'macOS-10.13'

variables:
  scheme: 'rakBibi'
  sdk: 'iphoneos'
  configuration: 'Release'
  teamId: M5H46J4YP8

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'chrisid_iOSDev_Nov2018.p12'
    #certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: '6ffac825-ed27-47d0-8134-95fcf37a666c.mobileprovision'

- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true
    exportOptions: 'specify'
    #exportMethod: 'development'
    exportTeamId: $(teamId)
    signingOption: 'nosign'
