trigger:
- master

pool:
  vmImage: 'macOS-10.13'

variables:
  scheme: 'rakBibi'
  sdk: 'iphoneos'
  configuration: 'Release'
  teamId: M5H46J4YP8

steps:
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true
    exportOptions: 'specify'
    #exportMethod: 'development'
    exportTeamId: $(teamId)
    signingOption: 'manual'
