# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'MC-Demo'
    method: 'POST'
    headers: '{
      "Content-Type":"application/json", 
      }'
    body: '{
        "name": "karasik@microfocus.com",
        "password": "Welc0me11"
      }'
    urlSuffix: '/rest/client/login'
    waitForCompletion: 'false'