trigger:
- master

pool:
  vmImage: 'macOS-10.13'

variables:
  scheme: 'rakBibi'
  sdk: 'iphoneos'
  configuration: 'Release'
  teamId: M5H46J4YP8

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'evgeny.karasik@gmail.com_cert.p12'
    #certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'evgeny.karasik.mobileprovision'

- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true
    exportTeamId: $(teamId)
    exportOptions: 'specify'
    exportMethod: 'development'
    signingOption: 'nosign'

